/** 操作ID,下一步操作ID,场景ID,操作类型,具体操作ID,描述 */

let messageObj = {
    910001: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）母亲大人，早上好啊！" },
    910002: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）我不好，你们什么公司啊。" },
    910003: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）大过节也不让人休息的，公司又不是只有你一个人的咯。" },
    910004: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）你们领导是成心不想让我抱外孙的？" },
    910005: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）妈！什么乱七八糟的啊！" },
    910006: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）客户是外国人嘛，他们又没有黄金周。" },
    910007: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）真的？" },
    910008: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）这资本主义国家，就是没人性。" },
    910009: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）而且这也是老板器重我嘛。" },
    910010: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）那相亲怎么办。" },
    910011: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）你帮帮忙，解释一下呗。" },
    910012: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）解释什么你也不小了，知道给你找个好男人多难吗？" },
    910013: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）上次你刘阿姨帮你介绍的那个大老板，自己有个大公司的。" },
    910014: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）我知道，那个万里挑一……" },
    910015: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）对，就是他，多少女孩子追着想嫁给他啊！" },
    910016: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）你倒好，一顿饭功夫不到，就把人给得罪了。" },
    910017: { nxId: 1, doing: 1, item: 91001, name:"母亲大人", head: "th_mother_ico", txt: "分支选择" },
    910018: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）妈，您别跟我提了，提起来我就要爆炸！" },
    910019: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）人家要的就是一个生育机器。" },
    910020: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）那那个销售小伙呢？戴个眼镜秀秀气气，跟你还是同行。" },
    910021: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）怎么说呢，有点一言难尽……" },
    910022: { nxId: 1, doing: 1, item: 91002, name:"母亲大人", head: "th_mother_ico", txt: "分支选择" },
    910023: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）妈，虽然我不想承认，但这个是真没瞧上您女儿！" },
    910024: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）是吗？好吧，也难怪。谁让我生个脾气这么差的女儿。" },
    910025: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）？？？妈，您这当头一锅来得相当突然啊。" },
    910026: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）那还有那个老实的小伙子呢？" },
    910027: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）……您别提他。提他我头疼" },
    910028: { nxId: 1, doing: 1, item: 91003, name:"母亲大人", head: "th_mother_ico", txt: "分支选择" },
    910029: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）哎，行了行了，反正你就是一堆的理由！" },
    910030: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）我告诉你，女人一到了这个岁数" },
    910031: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）（无奈）……就开始贬值……" },
    910032: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）一过了三十……" },
    910033: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）……就是赔钱货……" },
    910034: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）你还犟！我告诉你，过两年你就是想让别人挑别人都不会考虑！" },
    910035: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）你现在这也不喜欢，那也不想要，你到底想找个什么样的？" },
    910036: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）妈，我喜欢处着有感觉的，您别管了！" },
    910037: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）你不相处怎么知道喜不喜欢，处处就有感情了嘛。" },
    910038: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）这次更过分，直接放人家鸽子，下回谁还给你介绍。" },
    910039: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）那省的你们麻烦了！我不想找个三观不一样的！" },
    910040: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）话都说不到一起，你以后不要再给我安排了！" },
    910041: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）我就是搞不懂了，什么感觉，什么三观，那能当饭吃？" },
    910042: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）说什么都是假的，女人把自己嫁出去才是真的。" },
    910043: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）（黑线团表情）喂，喂，喂？" },
    910044: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）我听得见啊，你那边怎么了？" },
    910045: { nxId: -1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）妈妈，我进电梯了，信号特别不~~（挂断）" },

    920001: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）喂，哪位？" },
    920002: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程昱川）是我，程昱川。" },
    920003: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）（咦，是他？昨天在机场帮我解围的那个帅哥！）" },
    920004: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）（没想到真的给我打电话了！）" },
    920005: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）我记得你，昨天的事真是谢谢你了。" },
    920006: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）对了，现在国内是几点来着？在家时差倒过来了吗？" },
    920007: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程昱川）应该快下午3点了。我经常飞，不需要倒时差。" },
    920008: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程昱川）对了，林晓璐小姐，我有个不情之请。" },
    920009: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）请说。" },
    920010: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程昱川）我希望下一次见面的时候，能有幸请你一起共进午餐。" },
    920011: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）没问题。不过稍等一下……" },
    920012: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程昱川）嗯？" },
    920013: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）为什么是午餐？难道不是应该请女士晚餐的吗？" },
    920014: { nxId:-1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程昱川）（挂断）" },

    930001: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程昱川）喂，你去哪了，我这搞定了，我去找你吧。" },
    930002: { nxId:-1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）不用了吧，现在也不早了，待会儿酒店见吧。" },

    930003: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）学姐？" },
    930004: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）好你个林晓璐！听说你大过节的跑西班牙去了？" },
    930005: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）连我这个姐们儿都不叫上，不够意思吧？" },
    930006: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我是被迫的好吗。" },
    930007: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）怎么样，还好吧？" },
    930008: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）睡得挺好，今天还去逛了一大圈，我告诉你，我买了……" },
    930009: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）谁问你这个？有没有遇到什么帅哥啊？" },
    930010: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）你这人怎么这么八卦！" },
    930011: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）不八卦我打电话给你干啥？" },
    930012: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）遇是遇到了几个……" },
    930013: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）什么？几个？才一天功夫就几个？可以啊，平时没看出你这么能耐。" },
    930014: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）学姐你什么意思！" },
    930015: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）快说说都是些什么样的小哥哥。好久没这种开卧谈会的赶脚了。" },
    930016: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）嘻嘻。等我倒杯水慢慢和你说……" },
    930017: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）快快快！都是哪几个，帅不，你中意哪个？" },
    930018: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）一个一个说啊。" },
    //程昱川
    930019: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）程昱川这家伙虽然看起来有点轻佻。" },
    930020: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）但是实际想一想，还是个懂得分寸的人。" },
    930021: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）还是个年轻的霸道总裁。你要做玛丽苏了。" },
    930022: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）苏个头啊，我接着说啊。" },
    //顾廷巍
    930023: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）顾小弟很帅，脾气也很大，凶凶的。" },
    930024: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）虽然嫩了点，但是那种年轻人的活力最赞啦！" },
    930025: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你不是说他在机场看起来很渣男吗？" },
    930026: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）但是他之后偷偷哭被我发现了，估计有什么隐情吧。" },
    930027: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）也是，反正你对他有想法，什么借口都找的出来。" },
    930028: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）哈哈，知我者学姐！再说那个混血儿……" },
    //博文朗
    930029: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）那个混血的艺术家我很有好感。" },
    930030: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）文艺女青年，你小心点，别玩飘了。" },
    930031: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）他身上既有异域风情，又有那种中国人的亲切。我喜欢和他一起那种放松感。" },
    930032: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）还很老道。下次给你送画就是个绝佳的机会。" },
    930033: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）你懂的，嘿嘿嘿！" },
    930034: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）好啦，不跟你说了，我要睡会了，今天真的累，鞋也坏了。" },
    930035: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）那你早点休息吧。有最新进展记得告诉我啊！" },
    930036: { nxId:-1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）知道啦，学姐，拜拜。" },
    //博文朗邀约
    930037: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）美丽的小姐，晚上好。我是博文朗！" },
    930038: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）你的肖像我已经画好了。随时方便你来取。" },
    930039: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）好的，谢谢你啦！" },
    930040: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）顺便，我想邀请你到我的画室去看看，不知道你是否有时间？" },
    930041: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）这个……我需要看看行程安排再答复你。" },
    930042: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）我的工作室在锡切斯，离巴塞罗那很近，一个小时就能到。" },
    930043: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）那是个非常美丽的小镇，也是我成长的地方。" },
    930044: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）我考虑一下，尽快答复你。" },
    930045: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）好的，静候你的答复，晚安，美丽的小姐……" },
    930046: { nxId:-1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）谢谢，晚安……" },
    //顾廷巍兜风
    940001: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（我）喊这么大声干嘛！" },
    940002: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（顾）这里不好停车，你赶紧下来。" },
    940003: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（我）我答应要去了吗！再说了，我都出去走了一天了，很累啊！" },
    940004: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（顾）这次不收你钱。你只要带着眼睛就好。" },
    940005: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（我）那我可以考虑一下。   " },
    940006: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（顾）别想了，快点。" },
    940007: { nxId:-1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（顾）你等等，我换件衣服。" },
    //情感专家小天使
    940010: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）学姐，我有事想问你……" },
    940011: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你这个少女怀春的语气！所以你是选了哪个……" },
    940012: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）你也太敏锐了吧……博文朗啊……" },
    940013: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）上天保佑，铁树开花啊！快说快说！" },
    940014: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）虽然他约我出去玩，但是我有点担心是我想多了……" },
    940015: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你说你这个性格……你不仅身材，脑子也是电线杆成精啊！" },
    940016: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）喂！" },
    940017: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你管他是什么意思，你看上了就是你的！" },
    940018: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）发现目标，瞄准目标，然后“嘭”！他自然就会成为你的囊中之物。" },
    940019: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）嗯嗯嗯，受教受教！那小女子这就去啦！" },
    940020: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）记得随时给我汇报！加油加油，主动出击！" },
    940021: { nxId:-1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）拜拜，学姐。" },
    //情感专家小天使二段杀
    952011: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）这有什么好担心的，怎么你都不吃亏啊，赚了好吗？" },
    952012: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）我还想有这样的机会呢。可怜我周围都是些老帮菜。" },
    952013: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我又不是你，也不知道你哪来这么多欲火。" },
    952014: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）这是我的乐趣啊！你不懂！没开窍的小雏鸟。" },
    952015: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）那你现在在干嘛？还跟他在一起？" },
    952016: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）下午一起出去玩了，现在在他家。" },
    952017: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）姐妹，加油，你懂的。" },
    952018: { nxId:-1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）别闹，我挂了。" },
    //孟淑母上 //缺头像
    952019: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（陌）你是谁？" },
    952020: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（我）我是顾廷巍的女朋友，请问您是？" },
    952021: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（陌）你现在是不是和顾廷巍在一起！？" },
    952022: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（我）是的，他现在在忙，您有什么事，我可以转达……" },
    952023: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（陌）你这个贱人！好意思抢我女儿的男朋友！" },
    952024: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（我）……" },
    952025: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（陌）说话呀，贱女人，勾引小顾的xx，狐狸精！" },
    952026: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（我）我认识顾廷巍的时候，顾廷巍和你女儿就已经分手了！" },
    952027: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（我）而且你最好去问问你女儿，她究竟做了什么才让顾廷巍离开她的！" },
    952028: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（我）他们分手，与我无关！你最好弄清楚因果再来骂街，“阿姨”！" },
    952029: { nxId:1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（陌）你！你！胡说八道！你这贱女人，当初她爸爸就是被你们这种小狐狸精给迷了眼……" },
    952030: { nxId:-1, doing: 0, item: 0, name:"陌生女人", head: "th_common_ico", txt: "（我）不好意思，我没时间浪费在你这样的人身上！" },
    //情感专家小天使三段连杀
    952031: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我现在心里很难受！" },
    952032: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）怎么了，刚刚不还好好的。" },
    952033: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）刚刚他前女友的妈妈竟然给我打电话了，特别地恶毒。" },
    952034: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）这种阿姨说话最难听了。" },
    952035: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）极其地不开心，刚刚接电话的中途都想砸手机。" },
    952036: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）诶呀，你干嘛去在乎那种闲在家里没事干的老女人的话呢。" },
    952037: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）还有别的事儿，他带我去看他的演出，我没想到这里有有脱衣舞娘助兴的。" },
    952038: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）而且他上台之前，我看到他好像磕了药。" },
    952039: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）这有啥，国内也有脱衣肌肉男，就算他嗑药，也和你没关系啊。" },
    952040: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）关系吗？这很严重啊。" },
    952041: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）当然啊，你只是去度假，放松心情的。你还真想和他在一起啊。" },
    952042: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）不能吗？" },
    952043: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）天哪，你竟然认真了。傻妞，我前面怎么跟你说的。" },
    952044: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）那是你，我怎么可能这么洒脱！" },
    952045: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）那你想怎么办？报警抓他？劝他戒掉？你明天就要回来的呀。" },
    952046: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）你这样说让我更加焦虑了。" },
    952047: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）亲爱的，纯情浪漫不存在好吗？" },
    952048: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我又没想……" },
    952049: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）行行行，就你嘴硬。不过，就算你们在一起了，心理准备做好了吗？" },
    952050: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我不敢想，我只知道，这几天我很开心。" },
    952051: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）天哪，几天的逍遥时光让你忘了是吗！你们是根本不可能好吧。" },
    952052: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）凡事都是有可能的，总不能一棒子就敲定吧。" },
    952053: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我今天见了他的邻居，老伯年龄都那么大了，他依然会去追求自己的爱情。" },
    952054: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）这让你动容了？" },
    952055: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）也不是，只是觉得不想后悔。" },
    952056: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你可以考虑啊？但是你要问他怎么想的？" },
    952057: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）我们公司小年轻吵个架就分手，看上个谁随便扑的，完全我行我素。" },
    952058: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）他不一样。" },
    952059: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）行行行，我就是举个例。他还没毕业吧？还有几年啊？" },
    952060: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）不知道。" },
    952061: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）那你觉得他会回国？" },
    952062: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我没有问过他。" },
    952063: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你觉得他会跟你结婚吗？这些你也不问，你也不想吗？" },
    952064: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你把他领到你爸妈旁边会怎么样？" },//宁拆十座庙，不拆一桩婚
    952065: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）就算你爸妈同意，人家年龄那么小，怎么可能会想结婚啊！" },
    952066: { nxId:-1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）……" },
    //护花使者顾廷巍
    962001: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（顾）你去哪了！怎么找不到你，不是让你乖乖看我表演吗？" },
    962002: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（我）顾廷巍，呜呜，救我！" },
    962003: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（顾）怎么了？慢点说，别急。" },
    962004: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（我）我被两个人追着现在，顾廷巍你快点来救救我。" },
    962005: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（顾）我出来了，你出门以后往哪个方向走了？" },
    962006: { nxId:1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（我）右边，就直走，快来，他们一直跟着我。" },
    962007: { nxId:-1, doing: 0, item: 0, name:"顾廷巍", head: "th_gu_ico", txt: "（顾）等我！我马上过来。" },
    //情感专家小天使四杀连环
    962011: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你那边怎么样，突然都不回了。" },
    962012: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）刚刚我心思很乱，就想一个人待会，结果有人尾随我，他就赶过来救了我。" },
    962013: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）哇！英雄救美嘛，真好，羡慕你。" },
    962014: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）多大岁数了还犯花痴。" },
    962015: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）犯花痴是女人天生的权力好伐。" },
    962016: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）面对青春洋溢的面孔不去欣赏，才是对自己的残忍和对他们的不尊重。" },
    962017: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）可是我现在纠结死了。他跟我解释了，那些女的都是主办方安排的，逢场作戏。" },
    962018: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）还有，那个药片是薄荷糖。" },
    962019: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）那就都是误会啊，那你到底是怎么想的。" },
    962020: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）……我现在没什么主意……" },
    962021: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）亲爱的，说句很残忍的话 。当你到了风韵犹存的时候，他可是风华正茂。" },
    962022: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你是需要生活依靠的，你们可是异国恋啊！" },
    962023: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你妈那边怎么交代？你们能结婚吗？难道一直拖着？" },
    962024: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）其实我也不知道自己在做什么？" },
    962025: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我竟然有种冲动，不去想未来我们会遇到什么坎坷！" },
    962026: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）但是我又怕……难道我要告别吗？" },
    962027: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）对他说谢谢或者祝他好运？很抱歉，很可惜，还有些伤心。" },
    962028: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你最终还是精神失常了啊！" },
    962029: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）也许是吧。" },
    962030: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）那要不你告诉他吧。总不能困难都在你这一头咯。" },
    962031: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我要怎么说啊。" },
    962032: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）摊牌呀！看看他什么反应？" },
    962033: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你马上就要离开了，说或者不说只在你的一念之间。" },
    962034: { nxId:-1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）好吧，我知道了……" },
    //情感专家小天使，何处没有你的身影~
    963001: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）我在夜店呢！你等我一下我出去接。" },
    963002: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）嗯。" },
    963003: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）喂，宝贝怎么啦？" },
    963004: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）他带我出席了他的画展，还把画我的画介绍给了所有人。" },
    963005: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）我的天！你可以啊！这么快就攻下了。" },
    963006: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）那你还给我打电话，不跟他甜甜蜜蜜？" },
    963007: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）出了点意外，他前女友来现场闹自杀。现在被送去医院了。" },
    963008: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）啊！闹这么大？严不严重啊？不过，这个女人神经病吧。" },
    963009: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）可能是吧，我才知道。我心里很乱，我无法确定他对我是不是真心的。" },
    963010: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）他看到伊莲娜的样子，我有些害怕。" },
    963011: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）那他现在人呢？" },
    963012: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）送那个女人去医院了。" },
    963013: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你跟去呀。这种女人这么会来事，一哭二闹三上吊。" },
    963014: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）她是不是还在你面前装的一副可怜兮兮的样子？" },
    963015: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我觉得她是真的可怜。" },
    963016: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）一个原本那么风姿绰约的女人，把自己搞得有些疯疯癫癫，何必呢？" },
    963017: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）哎呦！这种绿茶，我见识的多了。" },
    963018: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）不这样，博文朗能回到她身边？赶紧去医院啊！" },
    963019: { nxId:-1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）敌情这么紧张，你不去，你想干嘛？" },
    //博文朗风中凌乱
    963020: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）为什么？" },
    963021: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）对不起，我怕我会动摇，然后就走不了了……" },
    963022: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）可以不走吗？" },
    963023: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）博文朗，我看不透你。也看不透你的感情。" },
    963024: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）在你提出请求之前，你先回答我。" },
    963025: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）你能对一段感情认真吗？你能再次承担起一段感情吗？" },
    963026: { nxId:1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（博）……我……" },
    963027: { nxId:-1, doing: 0, item: 0, name:"博文朗", head: "th_bo_ico", txt: "（我）等你想清楚，再告诉我吧。" },
    //骚扰程昱川
    951001: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程）喂……" },
    951002: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）程昱川，你还没起床吗？" },
    951003: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程）一大早的，睡个懒觉都不行么。" },
    951004: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）什么一大早，都9点了啊。" },
    951005: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程）大小姐，你出来度假的还是加班的啊。话说就在隔壁你为啥要打电话？" },
    951006: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）难道要我闯你的卧室？万一你有什么不良习惯，被我看到了怎么办？" },
    951007: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程）那不是正好。我闯过你的浴室，正好扯平了。" },
    951008: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）你怎么这么重的鼻音？" },
    951009: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程）我没什么，阿嚏！" },
    951010: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）着凉了吗？" },
    951011: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程）可能是昨晚那个海水浴……阿嚏！" },
    951012: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）你一会香水过敏一会海水着凉，抵抗力也太差了吧。" },
    951013: { nxId:1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（程）胡说八道，我身体好得很。" },
    951014: { nxId:-1, doing: 0, item: 0, name:"程昱川", head: "th_cheng_ico", txt: "（我）你给我老实等着。" },
    //情感杀手小天使，七星汇聚，莫得感情
    961001: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）宝贝，你明天是不是要回国了？你和那个大帅哥怎么样了？" },
    961002: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）不要提他了。" },
    961003: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）怎么了？" },
    961004: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）他有女朋友。" },
    961005: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）什么？！" },
    961006: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我刚看到了他和那个女人的短信，还有给她买的钻石项链。" },
    961007: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）……晓璐你别太难过了。" },
    961008: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我没有难过，只是愤怒！" },
    961009: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）这种渣男确实可恨。" },
    961010: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）之前所有对他的喜欢，这一刻就像条钻在心里的毒蛇，五脏六腑都是剜心的痛！" },
    961011: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）宝贝，千万不要为难自己。这种人不值得你在意他。" },
    961012: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）嗯，我不想再提他。" },
    961013: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）有些人天生就是混蛋，不用问自己为什么。" },
    961014: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我只是意难平。" },
    961015: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）嗯，没错，不要因为这种渣男让自己难受。" },
    961016: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）现在想想还真可笑，虚情假意也能演得这么像。" },
    961017: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）本来就是路边遇到的野男人。没啥好难过的。你现在在哪儿？" },
    961018: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）我搬出来了。不想这个人再出现在我视野里，微信电话也全删了。" },
    961019: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）明天的飞机？" },
    961020: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）嗯……啊？" },
    961021: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）怎么了？" },
    961022: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）明天接机的UBER，还是他给我订的。" },
    961023: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）你担心他通过这个找到你？" },
    961024: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）是。" },
    961025: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）逢场作戏的男人，谁会有这个精力来追回你啊。" },
    961026: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）说的也是。" },
    961027: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）再说了，他敢出现拦你，那最好不过了。" },
    961028: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）报警骚扰，让他吃不了兜着走。" },
    961029: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）有道理啊。" },
    961030: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）对了，记得给你的司机发消息告诉他你改了酒店。" },
    961031: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）你不说我还忘了……" },
    961032: { nxId:1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（天）都说恋爱中的女人智商低，我看你失恋了也……" },
    961033: { nxId:-1, doing: 0, item: 0, name:"我的小天使", head: "th_angel_ico", txt: "（我）学姐！" },
    //伏线收回，母上
    961040: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）囡囡啊，你在那边的工作做完了没有啊？" },
    961041: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）做完了做完了。" },
    961042: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）你老是忙工作，这对象也找不到。" },
    961043: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）回头好男人都被挑走了，你就知道哭了！" },
    961044: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）是是是，母上大人您说的都对。" },
    961045: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）你不要不耐烦我跟你说，我一说你就这个态度。" },
    961046: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）妈你放过我吧。我这还有事呢。" },
    961047: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）这次跟你约好的那个年轻人，人家妈妈跟我是同学呢。" },
    961048: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）还在等着回复，你要我怎么跟人家说？" },
    961049: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）我给你弄来了照片发过去了，你看看。" },
    961050: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）哼，我现在还稀罕这个？" },
    961051: { nxId: 1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（妈）什么？林晓璐你是不是单身太久脑子烧坏了？" },
    961052: { nxId: -1, doing: 0, item: 0, name:"母亲大人", head: "th_mother_ico", txt: "（我）行行行，我会看的。妈妈再见啊。" },
   


}

let selectObj = {
    91001: { count: 2, list: [100201, 0], pay: [0, 0], goodsId: [0, 0], txt: ["回忆当时情景", "实在不想回顾当初"], sound: ["effClick", "effClick"] },
    91002: { count: 2, list: [100232, 0], pay: [0, 0], goodsId: [0, 0], txt: ["回忆当时情景", "实在不想回顾当初"], sound: ["effClick", "effClick"] },
    91003: { count: 2, list: [100254, 0], pay: [0, 0], goodsId: [0, 0], txt: ["回忆当时情景", "跳过这个奇葩吧"], sound: ["effClick", "effClick"] },

}

export class CfgMessage {
    public msgs: any = messageObj;
    public selects: any = selectObj;
}